In [1]:
import deepchem as dc

# Define the featurizer parameters
acf = dc.feat.AtomicConvFeaturizer(
    frag1_num_atoms=100,     # Max atoms for ligand
    frag2_num_atoms=1000,    # Max atoms for protein pocket
    complex_num_atoms=1100,  # Sum of both
    max_num_neighbors=12,    # Max spatial neighbors per atom
    neighbor_cutoff=4.0      # Angstrom cutoff
)

# Load PDBBind using the complex featurizer
tasks, datasets, transformers = dc.molnet.load_pdbbind(
    featurizer=acf, 
    set_name='core',        # Use 'core' for quick testing, 'refined' for full training
    pocket=True             # Limits protein data to binding pocket to save memory
)

train_dataset, valid_dataset, test_dataset = datasets

No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
No normalization for NumAmideBonds. Feature removed!
No normalization for NumAtomStereoCenters. Feature removed!
No normalization for NumBridgeheadAtoms. Feature removed!
No normalization for NumHeterocycles. Feature removed!
No normalization for NumSpiroAtoms. Feature removed!
No normalization for NumUnspecifiedAtomStereoCenters. Feature removed!
No normalization for Phi. Feature removed!
Skipped loading some Tensorflow models, missing a dependency. No module named 'tensorflow'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
Skipped loading modules with transformers dependency. No module named 'transformers'
cannot import name 'HuggingFaceModel' from 'deepchem.models.torch_models' (/Users/reid/py/deepchemBenchmark/.venv/lib/python3.13/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading modules with pytorch-geome

In [2]:
import deepchem as dc

# Define the grid featurizer
grid_feat = dc.feat.RdkitGridFeaturizer(
    voxel_width=16/15.0,
    feature_types=['ecfp', 'hbond', 'splif', 'salt_bridge', 'charge'],
)

# Load PDBBind
tasks, datasets, transformers = dc.molnet.load_pdbbind(
    featurizer=grid_feat, 
    set_name='core',

)


No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
No normalization for NumAmideBonds. Feature removed!
No normalization for NumAtomStereoCenters. Feature removed!
No normalization for NumBridgeheadAtoms. Feature removed!
No normalization for NumHeterocycles. Feature removed!
No normalization for NumSpiroAtoms. Feature removed!
No normalization for NumUnspecifiedAtomStereoCenters. Feature removed!
No normalization for Phi. Feature removed!
Skipped loading some Tensorflow models, missing a dependency. No module named 'tensorflow'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
Skipped loading modules with transformers dependency. No module named 'transformers'
cannot import name 'HuggingFaceModel' from 'deepchem.models.torch_models' (/Users/reid/py/deepchemBenchmark/.venv/lib/python3.13/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading modules with pytorch-geome

In [4]:
train, val, test = datasets

In [ ]:
train.get_task_names()

array([0])

In [ ]:
train.ids

array(['1f8d', '1h23', '2jdy', '3dd0', '3su3', '3b3s', '2p4y', '1lol',
       '3gcs', '2j62', '2cbj', '3vh9', '2yki', '3udh', '3coy', '1f8b',
       '3muz', '1bcu', '2y5h', '3ehy', '4g8m', '2qbp', '2vo5', '3l4w',
       '2jdm', '3i3b', '2zcr', '2pq9', '2x0y', '1z95', '2obf', '1p1q',
       '3oe5', '1r5y', '2ole', '2zcq', '2v00', '3acw', '2j78', '10gs',
       '3ozt', '3u9q', '1zea', '2xys', '2fvd', '3cft', '3s8o', '1igj',
       '3cyx', '1lor', '2xdl', '3mfv', '3su2', '3d4z', '3bkk', '1u1b',
       '2wbg', '3g2n', '3nq3', '2iwx', '3su5', '3k5v', '2hb1', '1e66',
       '1sln', '1qi0', '2wca', '2wtv', '3f17', '1n1m', '3ueu', '3ejr',
       '3owj', '2cet', '3f3e', '3fk1', '2zxd', '1yc1', '2x00', '3pww',
       '3ag9', '3l3n', '1uto', '1n2v', '1vso', '3vd4', '2xnb', '2r23',
       '1kel', '2w66', '1sqa', '2brb', '2qbr', '4gid', '3b68', '2vot',
       '3pxf', '1loq', '1xd0', '3kgp', '2x97', '3e93', '2weg', '2xb8',
       '2v7a', '3kv2', '2d1o', '1mq6', '2zwz', '4des', '1nvq', '1w4o',
      

In [34]:
grid_feat.feature_types

[(False, 'ecfp'),
 (False, 'hbond'),
 (False, 'splif'),
 (False, 'salt_bridge'),
 (False, 'charge')]

In [33]:
grid_feat.FLAT_FEATURES

['ecfp_ligand', 'ecfp_hashed', 'splif_hashed', 'hbond_count']

In [32]:
grid_feat.VOXEL_FEATURES

['ecfp',
 'splif',
 'sybyl',
 'salt_bridge',
 'charge',
 'hbond',
 'pi_stack',
 'cation_pi']

In [31]:
grid_feat.cutoffs

{'hbond_dist_bins': [(2.2, 2.5), (2.5, 3.2), (3.2, 4.0)],
 'hbond_angle_cutoffs': [5, 50, 90],
 'splif_contact_bins': [(0, 2.0), (2.0, 3.0), (3.0, 4.5)],
 'ecfp_cutoff': 4.5,
 'sybyl_cutoff': 7.0,
 'salt_bridges_cutoff': 5.0,
 'pi_stack_dist_cutoff': 4.4,
 'pi_stack_angle_cutoff': 30.0,
 'cation_pi_dist_cutoff': 6.5,
 'cation_pi_angle_cutoff': 30.0}

In [28]:
train.X.shape

(154, 15, 15, 15, 37)

In [27]:
train.y

array([-0.80141645, -1.56910584, -1.70070974, -1.78405887, -1.16113377,
        1.22089675,  0.64183961,  0.20754675, -0.74877489,  1.12877402,
        0.60235844, -0.67419935,  0.31282987, -0.69174654,  0.08910324,
       -0.45047273, -0.80141645,  0.99717012, -1.38047359, -1.30151125,
        0.80853787, -1.58226623, -0.89792597,  1.06297207,  0.21632034,
       -0.17849134,  0.25141472, -0.45047273,  0.43566017, -0.51188788,
       -0.87599199,  0.3917922 ,  0.12858441,  0.91820779, -0.22674611,
        0.19877316, -0.20481212,  2.23424674,  0.99717012,  0.04084848,
        0.40495259, -0.06882143,  0.73834913, -0.97250152,  1.21212315,
       -1.32783203, -0.19165173,  0.86556623,  1.97103895, -0.73122771,
       -0.01617987,  0.91820779,  0.37424502, -1.78844567, -0.17849134,
       -0.15655736, -0.90231277, -0.59962381, -1.02952987,  0.09349004,
       -0.98127511,  0.55849047,  1.83066146,  1.01471731,  1.26037792,
       -1.04269026,  1.17264199,  2.15089761,  0.69009437,  0.30

In [22]:
import numpy as np
np.nan_to_num(np.array(train.X, dtype=np.float16))[0,6,5,6,:]

array([0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 5., 2., 1., 1., 0., 0., 1.,
       1., 0., 0.], dtype=float16)

In [24]:
# Shape and per-channel totals
print(np.nan_to_num(np.array(train.X, dtype=np.float16))[0].shape)
print(np.nan_to_num(np.array(train.X, dtype=np.float16))[0].sum(axis=(0, 1, 2)))   # activity per channel

# Which voxels have any signal at all?
occupied = (np.nan_to_num(np.array(train.X, dtype=np.float16))[0].sum(axis=-1) > 0)
print("Occupied voxels:", occupied.sum(), "/", occupied.size,f"end={occupied.sum()/occupied.size:.2%}")

# Just the charge channel (last one in your list) as a 3D scalar field
charge_map = np.nan_to_num(np.array(train.X, dtype=np.float16))[0, :, :, :, -1]

(15, 15, 15, 37)
[ 56.  13.   9.  23.   4.   6.   8.  38.   0.   2.   2.   0.   2.   0.
   6.   0.   0.   0.   0.  26.  16.   8.  30.  18.   8.  18.  10. 177.
 144. 113. 214. 102. 105. 154.  84.   0.   0.]
Occupied voxels: 157 / 3375 end=4.65%


In [37]:
# Build channel offsets for each per-voxel feature type in grid_feat.
X0 = np.nan_to_num(np.array(train.X, dtype=np.float16))[0]  # (nx, ny, nz, C)

# grid_feat.feature_types is a list of (is_flat, name) tuples.
voxel_types = [name for is_flat, name in grid_feat.feature_types if not is_flat]
flat_types  = [name for is_flat, name in grid_feat.feature_types if is_flat]
print("per-voxel:", voxel_types)
print("per-complex (not in X):", flat_types)

cuts = grid_feat.cutoffs
width_of = {
    "ecfp":        2 ** grid_feat.ecfp_power,
    "hbond":       len(cuts["hbond_dist_bins"]),
    "splif":       len(cuts["splif_contact_bins"]) * (2 ** grid_feat.splif_power),
    "salt_bridge": 1,
    "charge":      1,
    "sybyl":       len(grid_feat.sybyl_types),
    "pi_stack":    1,
    "cation_pi":   1,
}

offsets, start = {}, 0
for ft in voxel_types:
    w = width_of[ft]
    offsets[ft] = (start, start + w)
    start += w

print("computed total channels:", start, " actual X.shape[-1]:", X0.shape[-1])
print("offsets:", offsets)

per-voxel: ['ecfp', 'hbond', 'splif', 'salt_bridge', 'charge']
per-complex (not in X): []
computed total channels: 37  actual X.shape[-1]: 37
offsets: {'ecfp': (0, 8), 'hbond': (8, 11), 'splif': (11, 35), 'salt_bridge': (35, 36), 'charge': (36, 37)}


In [38]:
# Slice out just one feature type, e.g. hbond
ft = "hbond"
lo, hi = offsets[ft]
sub = X0[..., lo:hi]                     # shape (nx, ny, nz, width_of[ft])
print(ft, "sub-grid shape:", sub.shape)
print("nonzero voxels:", (sub.sum(axis=-1) > 0).sum())
print("per-channel totals:", sub.sum(axis=(0, 1, 2)))

hbond sub-grid shape: (15, 15, 15, 3)
nonzero voxels: 3
per-channel totals: [0. 2. 2.]
